# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# XXX on rainy day, changee to loop:
# https://www.vagrantup.com/docs/provisioning/ansible.html

Vagrant.configure(2) do |config|
  config.vm.box = "kashyyk/7Server"
  config.vm.define "web1" do |rhel|
          rhel.vm.hostname   = "web1"
          rhel.vm.box     = "kashyyk/7Server"
          rhel.vm.network :private_network, ip: "192.168.60.2", :netmask => "255.255.255.0"
          rhel.vm.provision :ansible do |ansible|
            ansible.playbook = "../absibles/prepare_rhel.yml"
          end
  end

  config.vm.define "web2" do |rhel|
          rhel.vm.hostname   = "web2"
          rhel.vm.box     = "kashyyk/7Server"
          rhel.vm.network :private_network, ip: "192.168.60.3", :netmask => "255.255.255.0"
          rhel.vm.provision :ansible do |ansible|
            ansible.playbook = "../absibles/prepare_rhel.yml"
          end
  end

  config.vm.define "db" do |rhel|
          rhel.vm.hostname   = "db"
          rhel.vm.box     = "kashyyk/7Server"
          rhel.vm.network :private_network, ip: "192.168.60.4", :netmask => "255.255.255.0"
          rhel.vm.provision :ansible do |ansible|
            ansible.playbook = "../absibles/prepare_rhel.yml"
          end
  end

  config.vm.provider "libvirt" do |vb|
    vb.memory = "512"
  end
end
