# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.ssh.insert_key = true
  config.vm.define "web1" do |rhel|
          rhel.vm.hostname   = "web1"
          rhel.vm.box     = "centos/7"
          rhel.vm.network :private_network, ip: "192.168.60.2"
  end

  config.vm.define "web2" do |rhel|
          rhel.vm.hostname   = "web2"
          rhel.vm.box     = "centos/7"
          rhel.vm.network :private_network, ip: "192.168.60.3"
  end

  config.vm.define "db" do |rhel|
          rhel.vm.hostname   = "db"
          rhel.vm.box     = "centos/7"
          rhel.vm.network :private_network, ip: "192.168.60.4"
  end

  config.vm.provider "libvirt" do |vb|
    vb.memory = "512"
  end
end
