# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "fedora/29-cloud-base"
  config.vm.provider "libvirt" do |lv|
    lv.memory = "1024"
  end
  config.ssh.insert_key = false
  config.ssh.private_key_path = ['~/.ssh/id_rsa', '~/.vagrant.d/insecure_private_key']
  config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "~/.ssh/authorized_keys"
  config.vm.define "fedora" do |box|
    box.vm.hostname   = "ikke-fedora"
    box.vm.provision :ansible do |ansible|
      ansible.playbook = "../ansibles/prepare_fedora.yml"
    end
  end
end
