# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "rhel-test" do |rhel|
          rhel.vm.hostname   = "rhel7-test"
          rhel.vm.box     = "generic/rhel7"
          rhel.vm.network :private_network, ip: "192.168.60.11", :netmask => "255.255.255.0"
          #rhel.playbook = "prepare_rhel.yml"
          rhel.vm.provision :ansible do |ansible|
            ansible.playbook = "../absibles/prepare_rhel7.yml"
          end
  end

  config.vm.provider "libvirt" do |vb|
    vb.memory = "1024"
  end
end
